stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: python:3.10
  before_script:
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - pytest

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t calculator-app .

deploy:
  stage: deploy
  script:
    - echo "Deployment step (optional for now)"
